# Generated by Django 6.0.1 on 2026-03-01 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_appointment_resulting_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='scheduled_pickup',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING_ACCEPTANCE', 'Waiting for Rider'), ('RIDER_ACCEPTED', 'Rider on the Way to Pick Up'), ('PICKED_UP', 'Picked Up'), ('PROCESSING', 'Washing / Processing'), ('READY_FOR_DELIVERY', 'Ready for Delivery'), ('OUT_FOR_DELIVERY', 'Out for Delivery'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING_ACCEPTANCE', max_length=20),
        ),
    ]
