# Generated by Django 6.0.1 on 2026-03-15 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='walkin_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
