# Generated by Django 6.0.1 on 2026-03-16 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_order_walkin_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_reference',
            field=models.CharField(blank=True, help_text='e.g. GCash Ref No.', max_length=100, null=True),
        ),
    ]
