# Generated by Django 6.0.1 on 2026-03-16 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_order_payment_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='item_type',
            field=models.CharField(choices=[('SERVICE', 'Service'), ('ADDON', 'Addon'), ('PRODUCT', 'Product')], default='SERVICE', max_length=10),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='load_index',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
