# Generated by Django 6.0.1 on 2026-03-16 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_orderitem_item_type_orderitem_load_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('WALK_IN', 'Walk-In'), ('DELIVERY', 'Delivery'), ('APPOINTMENT', 'Appointment')], default='WALK_IN', max_length=20),
        ),
    ]
