# Generated by Django 6.0.1 on 2026-03-30 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_order_order_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('WALK_IN', 'Walk-In'), ('DELIVERY', 'Delivery'), ('APPOINTMENT', 'Appointment'), ('DROP_OFF', 'Self Drop-Off')], default='WALK_IN', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('EXPECTING_DROP_OFF', 'Awaiting Customer Drop-Off'), ('PENDING_ACCEPTANCE', 'Waiting for Rider'), ('RIDER_ACCEPTED', 'Rider on the Way to Pick Up'), ('PICKED_UP', 'Picked Up'), ('AT_SHOP', 'At the Shop (Waiting for Processing)'), ('PROCESSING', 'Washing / Processing'), ('READY_FOR_DELIVERY', 'Ready for Delivery'), ('OUT_FOR_DELIVERY', 'Out for Delivery'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING_ACCEPTANCE', max_length=20),
        ),
        migrations.DeleteModel(
            name='CustomerProfile',
        ),
    ]
