# Generated by Django 6.0.1 on 2026-03-30 10:11

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_orderitem_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='receipt_token',
            field=models.CharField(blank=True, default=core.models.generate_receipt_token, max_length=12, null=True),
        ),
    ]
