# Generated by Django 6.0.1 on 2026-03-30 10:26

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_order_receipt_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='receipt_token',
            field=models.CharField(default=core.models.generate_receipt_token, editable=False, max_length=12, unique=True),
        ),
    ]
