# Generated by Django 6.0.1 on 2026-04-02 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_order_receipt_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_contact',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='release_method',
            field=models.CharField(choices=[('PICKUP', 'Customer Pickup'), ('DELIVERY', 'Deliver to Customer')], default='PICKUP', max_length=20),
        ),
    ]
