# Generated by Django 6.0.1 on 2026-04-02 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_order_delivery_address_order_delivery_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='delivery_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
