# Generated by Django 6.0.1 on 2026-04-15 04:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_adminotp_adminotpemail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminotpemail',
            name='user',
        ),
        migrations.CreateModel(
            name='UserOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashed_code', models.CharField(max_length=64)),
                ('purpose', models.CharField(choices=[('LOGIN', 'Login Verification'), ('EMAIL_CHANGE', 'Email Change Verification')], default='LOGIN', max_length=20)),
                ('expires_at', models.DateTimeField()),
                ('attempts', models.IntegerField(default=0)),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_otps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserOTPEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp_email', models.EmailField(help_text='Email address where security OTP codes are delivered.', max_length=254)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_otp_email', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='AdminOTP',
        ),
        migrations.DeleteModel(
            name='AdminOTPEmail',
        ),
    ]
