# Generated by Django 6.0.1 on 2026-04-15 05:02

from django.db import migrations


def clear_dummy_emails(apps, schema_editor):
    User = apps.get_model('core', 'User')
    UserOTPEmail = apps.get_model('core', 'UserOTPEmail')
    
    targets = ['rider', 'customer', 'employee']
    
    for user in User.objects.all():
        # Check if username or email matches any of the targets
        if any(target in user.username.lower() for target in targets) or \
           any(target in (user.email or '').lower() for target in targets):
             
            user.email = ''
            user.save()
            
            # Wipe OTP email if exists
            UserOTPEmail.objects.filter(user=user).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_adminotpemail_user_userotp_userotpemail_and_more'),
    ]

    operations = [
        migrations.RunPython(clear_dummy_emails),
    ]
